module ShiftyRequest
  class Command
    @argv: Array[String]
    @edit_attendance: EditAttendance

    def initialize:(Array[string]) -> untyped
    def self.run:(Array[String]) -> untyped

    def run: -> untyped
  end
end
