module ShiftyRequest
  class Command
    @argv: Array[String]
    @edit_attendance: Request::EditAttendance
    @load_attendance: LoadAttendance

    @make_edit_attendance_service: Service::MakeEditAttendanceService

    def initialize:(Array[string]) -> untyped
    def self.run:(Array[String]) -> untyped

    def load_attendances_history: -> Array[Model::EditAttendance]

    def load_working_time: -> WorkTime

    def run: -> untyped

    def send_edit_request: -> void

    def working_time: -> WorkTime
  end
end
