module ActiveSupport
  module Cache
    module Strategy
      module LocalCache
        module LocalCacheRegistry
          def cache_for: (untyped local_cache_key) -> untyped
          def set_cache_for: (untyped local_cache_key, untyped value) -> untyped
          extend LocalCacheRegistry
        end
      end
    end
  end
end
