module ShiftyRequest
  module Request
    class EditAttendance
      def body: (Model::EditAttendance, Model::WorkingTime) -> Hash[untyped, String]

      def call: (edit_attendances: Array[Model::EditAttendance], working_time: Model::WorkingTime) -> untyped

      def url: -> String
    end
  end
end
