module ShiftyRequest
  module Request
    class EditAttendance
      def body: (Model::EditAttendance) -> Hash[untyped, String]

      def call: (Array[Model::EditAttendance]) -> untyped

      def url: -> String
    end
  end
end
